name: CPS UI Kit - Bump, Build & Publish

on:
  push:
    branches:
      - 'master'
    paths:
      - 'projects/cps-ui-kit/**'
      - '.github/workflows/cps-ui-kit-publish.yml'

permissions:
  contents: read

jobs:
  version-bump:
    if: "!contains(github.event.head_commit.message, 'Bump version to') && !contains(github.event.head_commit.message, '#SkipVersionBump')"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Use Node.js v22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x

      - name: Bump version
        id: bump
        working-directory: projects/cps-ui-kit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          version=$(npm version minor -m "Bump version to %s")
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Commit and push
        working-directory: projects/cps-ui-kit
        run: |
          git add package.json
          git commit -m "Bump version to ${{ steps.bump.outputs.version }}"
          git push origin HEAD:master

  publish:
    needs: version-bump
    runs-on: ubuntu-latest
    if: always() && !cancelled() && !failure() && !contains(github.event.head_commit.message, 'Bump version to')
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch latest commits
        run: git pull origin master

      - name: Use Node.js v24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build CPS UI Kit Component Library
        run: npm run build

      - name: Print current version
        working-directory: dist/cps-ui-kit
        run: npm version

      - name: Publish to NPM registry
        working-directory: dist/cps-ui-kit
        run: NODE_AUTH_TOKEN="" npm publish
