name: CPS UI Kit - Bump, Build & Publish

on:
  push:
    branches:
      - 'master'
    paths:
      - 'projects/cps-ui-kit/**'
      - '.github/**'

jobs:
  bump_build_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js v16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - name: Bump version and create a new commit
        working-directory: projects/cps-ui-kit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version minor -m "Bump version to %s"
          git push origin HEAD:master --follow-tags

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: projects/cps-ui-kit/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('projects/cps-ui-kit/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm ci --production

      - name: Build CPS UI Kit Component Library
        run: npm run build

      - name: Publish to NPM registry
        working-directory: dist/cps-ui-kit
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
