name: CPS UI Kit - Bump Version

on:
  push:
    branches:
      - 'master'
    paths:
      - 'projects/cps-ui-kit/**'

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check commit message
        run: |
          commit_message=$(git log --format=%B -n 1)
          if [[ "$commit_message" == *"Bump version"* ]]; then
            echo "Commit message contains 'Bump version'. Skipping job execution."
            exit 1
          fi

      - name: Use Node.js v16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Bump version and create a new commit
        working-directory: projects/cps-ui-kit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version minor -m "Bump version to %s"
          git push origin HEAD:master --follow-tags
